In [ ]:
import numpy as np
import pandas as pd
from google.colab import files
import io

In [ ]:
%ls /gdrive/MyDrive/Thesis

ls: cannot access '/gdrive/MyDrive/Thesis': No such file or directory

In [ ]:
# df_reviews = pd.read_csv("/gdrive/MyDrive/Thesis/Final Dataset/airbnb reviews_indonesia_v1.csv")
# df_reviews.head()

In [ ]:
# df_scores = pd.read_csv("/gdrive/MyDrive/Thesis/Final Dataset/airbnb score rooms_indonesia_v1.csv")
# df_scores.head()

In [ ]:
# df_rooms = pd.read_csv("/gdrive/MyDrive/Thesis/Final Dataset/airbnb rooms_indonesia_v1.csv")
# df_rooms.head()

In [ ]:
# uploaded = files.upload()
df_scores = pd.read_csv(io.BytesIO(uploaded['airbnb score rooms_indonesia_v1.csv']))
# df_scores = pd.read_csv("/content/airbnb score rooms_indonesia_v1.csv")

Saving airbnb score rooms_indonesia_v1.csv to airbnb score rooms_indonesia_v1.csv

In [ ]:
df_scores.head()

,room_id,kebersihan,keakuratan,komunikasi,lokasi,check_in,nilai_ekonomis,number_of_reviews,grand_score
0,691493124521517277,5.0,4.9,4.9,4.6,4.9,4.8,30,4.83
1,39329971,5.0,5.0,5.0,4.8,5.0,4.8,32,4.97
2,21166693,4.7,4.8,4.9,5.0,5.0,4.9,81,4.85
3,11304489,5.0,5.0,5.0,4.8,5.0,5.0,141,5.00
4,20869672,4.9,4.9,4.8,4.7,4.9,4.8,19,4.84

In [ ]:
df = pd.read_csv("/content/cleaned thesis data.csv", sep='\t')
df.head()

,Unnamed: 0,room_id,reviewer_name,review_date,review_content,review_hash,clean_date,room_id-2,city,area,price,name,rating,number_of_reviews,desc,review_translated,clean_reviews,clean_reviews_v2
0,0,1016153.0,Maarten,September 2014,"It is a little hard to find, but once you find...",9afc72ba3d60211710475c7022ef6119,2014-09-01,1016153.0,bali,"selemadeg barat, bali",Rp1.775.094 per malam,Pondok di Balian Beach,4.85,286,RUMAH POHON BALIAN dengan kolam renang yang indah,"It is a little hard to find, but once you find...",it is a little hard to find but once you find ...,little hard find find little slice heaven situ...
1,1,1016153.0,Ivan,September 2014,We had great experience at Miryam's villa. The...,76685d2a27bc09c18ac43f1c5422e2fb,2014-09-01,1016153.0,bali,"selemadeg barat, bali",Rp1.775.094 per malam,Pondok di Balian Beach,4.85,286,RUMAH POHON BALIAN dengan kolam renang yang indah,We had great experience at Miryam's villa. The...,we had great experience at miryams villa the l...,great experience miryams villa location quiet ...
2,2,1016153.0,Hans,Juli 2014,Heerlijk relaxed en goed geregeld. geweldig ui...,1ec0f4d7b825668e7cca1a7fefce75ff,2014-07-01,1016153.0,bali,"selemadeg barat, bali",Rp1.775.094 per malam,Pondok di Balian Beach,4.85,286,RUMAH POHON BALIAN dengan kolam renang yang indah,Wonderfully relaxed and well arranged. Great v...,wonderfully relaxed and well arranged great vi...,wonderfully relaxed well arranged great view c...
3,3,1016153.0,Aldo,Januari 2014,"Brilliant house, beautifully located among a l...",58554fb2d1d90e1dca3e6382f71b1bbb,2014-01-01,1016153.0,bali,"selemadeg barat, bali",Rp1.775.094 per malam,Pondok di Balian Beach,4.85,286,RUMAH POHON BALIAN dengan kolam renang yang indah,"Brilliant house, beautifully located among a l...",brilliant house beautifully located among a lo...,brilliant house beautifully located among lot ...
4,4,1016153.0,Anna-Lena,Oktober 2014,Wir hatten eine tolle Zeit in Miryams Mushroom...,b44f1cbed8cae063f59118c31efdacba,2014-10-01,1016153.0,bali,"selemadeg barat, bali",Rp1.775.094 per malam,Pondok di Balian Beach,4.85,286,RUMAH POHON BALIAN dengan kolam renang yang indah,We had a great time in Miryam's Mushroom Villa...,we had a great time in miryams mushroom villat...,great miryams mushroom villathe villa well equ...

In [ ]:
df.drop('Unnamed: 0', axis=1, inplace=True)

# Descriptive Statistics

In [ ]:
len(df)

361317

exclude missing values

In [ ]:
df = df[df['clean_reviews_v2'].notna()]

In [ ]:
df.reset_index(drop=True, inplace=True)

Info and Describe

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 361150 entries, 0 to 361149
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   room_id            361150 non-null  float64
 1   reviewer_name      361150 non-null  object
 2   review_date        361150 non-null  object
 3   review_content     361150 non-null  object
 4   review_hash        361150 non-null  object
 5   clean_date         361150 non-null  object
 6   room_id-2          361150 non-null  float64
 7   city               361150 non-null  object
 8   area               361150 non-null  object
 9   price              361150 non-null  object
 10  name               361150 non-null  object
 11  rating             361150 non-null  float64
 12  number_of_reviews  361150 non-null  int64
 13  desc               361150 non-null  object
 14  review_translated  361150 non-null  object
 15  clean_reviews      361150 non-null  object
 16  clean_reviews_v2   361150 non-null  object
dtypes: float64(3), int64(1), object(13)
memory usage: 46.8+ MB

In [ ]:
df_scores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11461 entries, 0 to 11460
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   room_id            11461 non-null  int64
 1   kebersihan         11461 non-null  float64
 2   keakuratan         11461 non-null  float64
 3   komunikasi         11461 non-null  float64
 4   lokasi             11461 non-null  float64
 5   check_in           11461 non-null  float64
 6   nilai_ekonomis     11461 non-null  float64
 7   number_of_reviews  11461 non-null  int64
 8   grand_score        11461 non-null  float64
dtypes: float64(7), int64(2)
memory usage: 806.0 KB

In [ ]:
df[["rating","number_of_reviews"]].describe()

              rating  number_of_reviews
count  361150.000000      361150.000000
mean        4.771666         120.981180
std         0.181143         124.850705
min         2.250000           3.000000
25%         4.690000          41.000000
50%         4.810000          86.000000
75%         4.900000         157.000000
max         5.000000        1209.000000

In [ ]:
# df_scores.describe()
df_scores.iloc[:,1:].describe()

,kebersihan,keakuratan,komunikasi,lokasi,check_in,nilai_ekonomis,number_of_reviews,grand_score
count,11461.000000,11461.000000,11461.000000,11461.000000,11461.000000,11461.000000,11461.000000,11461.000000
mean,4.668467,4.766635,4.840023,4.708472,4.844516,4.726193,39.570020,4.744363
std,0.336236,0.267465,0.224897,0.273272,0.212195,0.274179,55.860107,0.277246
min,2.300000,2.000000,2.300000,2.300000,2.300000,1.700000,3.000000,2.250000
25%,4.500000,4.700000,4.800000,4.600000,4.800000,4.600000,7.000000,4.650000
50%,4.800000,4.800000,4.900000,4.800000,4.900000,4.800000,19.000000,4.820000
75%,4.900000,4.900000,5.000000,4.900000,5.000000,4.900000,48.000000,4.940000
max,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,1227.000000,5.000000

clean date

In [ ]:
df['clean_date'] = pd.to_datetime(df['clean_date'])

In [ ]:
df = df.set_index(df['clean_date'])
df = df.sort_index()

In [ ]:
# extract year

In [ ]:
df['year'] = pd.DatetimeIndex(df['clean_date']).year

In [ ]:
df.head(2)

,room_id,reviewer_name,review_date,review_content,review_hash,clean_date,room_id-2,city,area,price,name,rating,number_of_reviews,desc,review_translated,clean_reviews,clean_reviews_v2,year
clean_date,,,,,,,,,,,,,,,,,,
2011-04-01,83508.0,Wesley,April 2011,When we stayed the staff we had were amongst t...,477dd66a710fa00446a2606be517348e,2011-04-01,83508.0,bali,"finns beach club, bali","Rp2.787.247 per malam, awalnya Rp3.582.365",Vila di Kuta,4.69,104,TERAS SAWAH YANG TENANG CANGGU VILLA 3 KAMAR T...,When we stayed the staff we had were amongst t...,when we stayed the staff we had were amongst t...,stayed staff amongst friendly helpful balinese...,2011
2012-01-01,286363.0,Nathan,Januari 2012,We stayed at the Jungalow for three nights and...,1e75f87ac50e174bf32af3898f0f7e6d,2012-01-01,286363.0,bali,"abiansemal, bali",Rp1.496.853 per malam,Pondok di Ubud,4.54,109,The Nest - Jungalow menghadap Sungai Ayung,We stayed at the Jungalow for three nights and...,we stayed at the jungalow for three nights and...,stayed jungalow three nights wonderful comfort...,2012

group by city and year

In [ ]:
# group by city and year
import plotly.express as px

In [ ]:
df_bali = df[df["city"] == "bali"]
df_jakarta = df[df["city"] == "jakarta"]
df_lombok = df[df["city"] == "lombok"]
df_bandung = df[df["city"] == "bandung"]
df_surabaya = df[df["city"] == "surabaya"]

In [ ]:
# df_grouped = df.groupby(['year']).size().reset_index(name='counts')
# df_grouped

In [ ]:
# px.line(df_grouped, x="year", y="counts", title = 'Number of reviews each year')

Bali

In [ ]:
df_bali_grouped = df_bali.groupby(['year']).size().reset_index(name='counts_bali_reviews')
df_bali_grouped

    year  counts_bali_reviews
0   2011                    1
1   2012                   48
2   2013                  330
3   2014                 1521
4   2015                 4195
5   2016                 9274
6   2017                16463
7   2018                25926
8   2019                40164
9   2020                13713
10  2021                 7636
11  2022                54114
12  2023                39823

In [ ]:
px.line(df_bali_grouped, x="year", y="counts_bali_reviews", title = 'Bali: Number of reviews each year')

In [ ]:
df_bali_room_grouped = df_bali.groupby(['year','room_id']).size().reset_index(name='counts')
df_bali_room_grouped

       year       room_id  counts
0      2011  8.350800e+04       1
1      2012  3.615800e+04       1
2      2012  5.765200e+04       2
3      2012  7.159500e+04       2
4      2012  2.810190e+05       3
...     ...           ...     ...
17710  2023  8.837894e+17       3
17711  2023  8.845209e+17       5
17712  2023  8.858648e+17       3
17713  2023  8.872685e+17       5
17714  2023  8.922616e+17       6

[17715 rows x 3 columns]

In [ ]:
df_bali_room_grouped = df_bali_room_grouped.groupby(['year']).size().reset_index(name='counts_bali_rooms')
df_bali_room_grouped

    year  counts_bali_rooms
0   2011                  1
1   2012                 16
2   2013                 47
3   2014                135
4   2015                325
5   2016                619
6   2017                984
7   2018               1520
8   2019               2222
9   2020               2111
10  2021               1177
11  2022               3976
12  2023               4582

In [ ]:
px.line(df_bali_room_grouped, x="year", y="counts_bali_rooms", title = 'Bali: Number of rooms each year')

Jakarta

In [ ]:
df_jakarta_grouped = df_jakarta.groupby(['year']).size().reset_index(name='counts_jakarta_reviews')
df_jakarta_grouped

    year  counts_jakarta_reviews
0   2013                      21
1   2014                     102
2   2015                     264
3   2016                     890
4   2017                    2841
5   2018                    5856
6   2019                    9339
7   2020                    5857
8   2021                    6649
9   2022                   14153
10  2023                    6977

In [ ]:
px.line(df_jakarta_grouped, x="year", y="counts_jakarta_reviews", title = 'Jakarta: Number of reviews each year')

In [ ]:
df_jakarta_room_grouped = df_jakarta.groupby(['year','room_id']).size().reset_index(name='counts')
df_jakarta_room_grouped

      year       room_id  counts
0     2013  9.499760e+05       1
1     2013  9.588020e+05       6
2     2013  1.272109e+06       3
3     2013  1.482245e+06       7
4     2013  1.584528e+06       2
...    ...           ...     ...
5795  2023  8.676163e+17       4
5796  2023  8.679828e+17       3
5797  2023  8.691286e+17       7
5798  2023  8.692159e+17       4
5799  2023  8.749420e+17       3

[5800 rows x 3 columns]

In [ ]:
df_jakarta_room_grouped = df_jakarta_room_grouped.groupby(['year']).size().reset_index(name='counts_jakarta_rooms')
df_jakarta_room_grouped

    year  counts_jakarta_rooms
0   2013                     6
1   2014                    13
2   2015                    31
3   2016                   102
4   2017                   251
5   2018                   446
6   2019                   707
7   2020                   773
8   2021                   845
9   2022                  1325
10  2023                  1301

In [ ]:
px.line(df_jakarta_room_grouped, x="year", y="counts_jakarta_rooms", title = 'Jakarta: Number of rooms each year')

try concat (trial)

In [ ]:
# result = pd.concat([df_bali_room_grouped, df_jakarta_room_grouped], axis=1)
# result

result = df_bali_room_grouped.join(df_jakarta_room_grouped.set_index('year'), on='year')
result

    year  counts_bali_rooms  counts_jakarta_rooms
0   2011                  1                   NaN
1   2012                 16                   NaN
2   2013                 47                   6.0
3   2014                135                  13.0
4   2015                325                  31.0
5   2016                619                 102.0
6   2017                984                 251.0
7   2018               1520                 446.0
8   2019               2222                 707.0
9   2020               2111                 773.0
10  2021               1177                 845.0
11  2022               3976                1325.0
12  2023               4582                1301.0

In [ ]:
result = result.join(df_lombok_room_grouped.set_index('year'), on='year')
result

    year  counts_bali_rooms  counts_jakarta_rooms  counts_lombok_rooms
0   2011                  1                   NaN                  NaN
1   2012                 16                   NaN                  1.0
2   2013                 47                   6.0                  8.0
3   2014                135                  13.0                 27.0
4   2015                325                  31.0                 66.0
5   2016                619                 102.0                136.0
6   2017                984                 251.0                217.0
7   2018               1520                 446.0                278.0
8   2019               2222                 707.0                430.0
9   2020               2111                 773.0                367.0
10  2021               1177                 845.0                200.0
11  2022               3976                1325.0                677.0
12  2023               4582                1301.0                700.0

In [ ]:
result.columns[1]

'counts_bali_rooms'

In [ ]:
px.line(result, x="year", y=result.columns[1:], title = 'Number of rooms each year')

Lombok

In [ ]:
df_lombok_grouped = df_lombok.groupby(['year']).size().reset_index(name='counts_lombok_reviews')
df_lombok_grouped

    year  counts_lombok_reviews
0   2012                      4
1   2013                     55
2   2014                    208
3   2015                    722
4   2016                   1646
5   2017                   2600
6   2018                   3018
7   2019                   5641
8   2020                   1860
9   2021                   1062
10  2022                   7603
11  2023                   5610

In [ ]:
px.line(df_lombok_grouped, x="year", y="counts_lombok_reviews", title = 'Lombok: Number of reviews each year')

In [ ]:
df_lombok_room_grouped = df_lombok.groupby(['year','room_id']).size().reset_index(name='counts')
df_lombok_room_grouped

      year       room_id  counts
0     2012  2.780580e+05       4
1     2013  2.780580e+05       3
2     2013  9.698590e+05       8
3     2013  9.740440e+05      19
4     2013  9.805570e+05      11
...    ...           ...     ...
3102  2023  8.633618e+17       4
3103  2023  8.634811e+17       7
3104  2023  8.663413e+17       3
3105  2023  8.668987e+17       4
3106  2023  8.694890e+17       4

[3107 rows x 3 columns]

In [ ]:
df_lombok_room_grouped = df_lombok_room_grouped.groupby(['year']).size().reset_index(name='counts_lombok_rooms')
df_lombok_room_grouped

    year  counts_lombok_rooms
0   2012                    1
1   2013                    8
2   2014                   27
3   2015                   66
4   2016                  136
5   2017                  217
6   2018                  278
7   2019                  430
8   2020                  367
9   2021                  200
10  2022                  677
11  2023                  700

In [ ]:
px.line(df_lombok_room_grouped, x="year", y="counts_lombok_rooms", title = 'Lombok: Number of rooms each year')

Bandung

In [ ]:
df_bandung_grouped = df_bandung.groupby(['year']).size().reset_index(name='counts_bandung_reviews')
df_bandung_grouped

    year  counts_bandung_reviews
0   2013                       1
1   2014                       7
2   2015                     100
3   2016                     639
4   2017                    2464
5   2018                    4849
6   2019                    7625
7   2020                    6340
8   2021                    7344
9   2022                   10653
10  2023                    4274

In [ ]:
px.line(df_bandung_grouped, x="year", y="counts_bandung_reviews", title = 'Bandung: Number of reviews each year')

In [ ]:
df_bandung_room_grouped = df_bandung.groupby(['year','room_id']).size().reset_index(name='counts')
df_bandung_room_grouped

      year       room_id  counts
0     2013  1.035015e+06       1
1     2014  2.407266e+06       6
2     2014  3.484263e+06       1
3     2015  9.737680e+05      11
4     2015  1.949845e+06       3
...    ...           ...     ...
3511  2023  8.708428e+17       3
3512  2023  8.726277e+17       7
3513  2023  8.727571e+17       6
3514  2023  8.727998e+17       3
3515  2023  8.736625e+17       7

[3516 rows x 3 columns]

In [ ]:
df_bandung_room_grouped = df_bandung_room_grouped.groupby(['year']).size().reset_index(name='counts_bandung_rooms')
df_bandung_room_grouped

    year  counts_bandung_rooms
0   2013                     1
1   2014                     2
2   2015                    15
3   2016                    61
4   2017                   150
5   2018                   267
6   2019                   415
7   2020                   488
8   2021                   560
9   2022                   793
10  2023                   764

In [ ]:
px.line(df_bandung_room_grouped, x="year", y="counts_bandung_rooms", title = 'Bandung: Number of rooms each year')

Surabaya

In [ ]:
df_surabaya_grouped = df_surabaya.groupby(['year']).size().reset_index(name='counts_surabaya_reviews')
df_surabaya_grouped

    year  counts_surabaya_reviews
0   2013                        1
1   2014                       60
2   2015                      219
3   2016                      575
4   2017                     1185
5   2018                     2244
6   2019                     4224
7   2020                     2267
8   2021                     2272
9   2022                     5012
10  2023                     2609

In [ ]:
px.line(df_surabaya_grouped, x="year", y="counts_surabaya_reviews", title = 'Surabaya: Number of reviews each year')

In [ ]:
df_surabaya_room_grouped = df_surabaya.groupby(['year','room_id']).size().reset_index(name='counts')
df_surabaya_room_grouped

      year       room_id  counts
0     2013  1.841843e+06       1
1     2014  3.578420e+05       6
2     2014  1.265144e+06       2
3     2014  1.841843e+06      21
4     2014  2.438172e+06      31
...    ...           ...     ...
2376  2023  8.676232e+17       5
2377  2023  8.700437e+17       4
2378  2023  8.701227e+17       3
2379  2023  8.733537e+17       4
2380  2023  8.737904e+17       5

[2381 rows x 3 columns]

In [ ]:
df_surabaya_room_grouped = df_surabaya_room_grouped.groupby(['year']).size().reset_index(name='counts_surabaya_rooms')
df_surabaya_room_grouped

    year  counts_surabaya_rooms
0   2013                      1
1   2014                      4
2   2015                     20
3   2016                     44
4   2017                    104
5   2018                    178
6   2019                    331
7   2020                    310
8   2021                    328
9   2022                    541
10  2023                    520

In [ ]:
px.line(df_surabaya_room_grouped, x="year", y="counts_surabaya_rooms", title = 'Surabaya: Number of rooms each year')

aggregate visualization

In [ ]:
# result = df_bali_grouped.join(df_jakarta_grouped.set_index('year'), on='year')
# result

In [ ]:
# result = result.join(df_lombok_grouped.set_index('year'), on='year')
# result

In [ ]:
# result = result.join(df_bandung_grouped.set_index('year'), on='year')
# result

In [ ]:
# result = result.join(df_surabaya_grouped.set_index('year'), on='year')
# result

In [ ]:
result

,year,counts_bali_reviews,counts_jakarta_reviews,counts_lombok_reviews,counts_bandung_reviews,counts_surabaya_reviews
0,2011,1,1.0,1.0,1.0,1.0
1,2012,48,10.0,23.0,12.0,17.0
2,2013,330,33.0,55.0,51.0,47.0
3,2014,1521,102.0,208.0,71.0,60.0
4,2015,4195,264.0,722.0,100.0,219.0
5,2016,9274,890.0,1646.0,639.0,575.0
6,2017,16463,2841.0,2600.0,2464.0,1185.0
7,2018,25926,5856.0,3018.0,4849.0,2244.0
8,2019,40164,9339.0,5641.0,7625.0,4224.0
9,2020,13713,5857.0,1860.0,6340.0,2267.0
10,2021,7636,6649.0,1062.0,7344.0,2272.0
11,2022,54114,14153.0,7603.0,10653.0,5012.0
12,2023,39823,6977.0,5610.0,4274.0,2609.0

In [ ]:
px.line(result, x="year", y=result.columns[1:], title = 'Number of reviews each year')

In [ ]:
# result_rooms = df_bali_room_grouped.join(df_jakarta_room_grouped.set_index('year'), on='year')
# result_rooms

In [ ]:
# result_rooms = result_rooms.join(df_lombok_room_grouped.set_index('year'), on='year')
# result_rooms

In [ ]:
# result_rooms = result_rooms.join(df_bandung_room_grouped.set_index('year'), on='year')
# result_rooms

In [ ]:
# result_rooms = result_rooms.join(df_surabaya_room_grouped.set_index('year'), on='year')
# result_rooms

In [ ]:
result_rooms

,year,counts_bali_rooms,counts_jakarta_rooms,counts_lombok_rooms,counts_bandung_rooms,counts_surabaya_rooms
0,2011,1,1.0,1.0,1.0,1.0
1,2012,16,3.0,2.0,3.0,5.0
2,2013,47,6.0,8.0,7.0,10.0
3,2014,135,13.0,27.0,11.0,17.0
4,2015,325,31.0,66.0,15.0,20.0
5,2016,619,102.0,136.0,61.0,44.0
6,2017,984,251.0,217.0,150.0,104.0
7,2018,1520,446.0,278.0,267.0,178.0
8,2019,2222,707.0,430.0,415.0,331.0
9,2020,2111,773.0,367.0,488.0,310.0
10,2021,1177,845.0,200.0,560.0,328.0
11,2022,3976,1325.0,677.0,793.0,541.0
12,2023,4582,1301.0,700.0,764.0,520.0

In [ ]:
px.line(result_rooms, x="year", y=result_rooms.columns[1:], title = 'Number of rooms each year')

--------------------------------------

In [ ]:
df['city'].nunique()

5

In [ ]:
# df['price'].nunique()

Numerical Data

In [ ]:
# ### Example
# data = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

# mean = np.mean(data)
# median = np.median(data)
# std_dev = np.std(data)
# min_val = np.min(data)
# max_val = np.max(data)

In [ ]:
# quartiles = np.percentile(data, [25, 50, 75])  # 25th, 50th (median), and 75th percentiles
# range_val = np.ptp(data)  # Range (maximum - minimum)
# correlation = np.corrcoef(data1, data2)  # Correlation between two numerical variables

Categorical Data

In [ ]:
# ### Example
# data = pd.Series(['red', 'blue', 'green', 'red', 'blue', 'yellow'])

# count = data.value_counts()  # Count of each category
# unique_count = data.nunique()  # Count of unique categories
# mode = data.mode()  # Most frequent category

In [ ]:
# import matplotlib.pyplot as plt

# count.plot(kind='bar')
# plt.xlabel('Category')
# plt.ylabel('Count')
# plt.show()

Text Data

In [ ]:
# import nltk
# from nltk import FreqDist

In [ ]:
# data = [
#     "I like to eat apples.",
#     "Apples are delicious.",
#     "I prefer oranges over apples.",
# ]

# # Tokenize the text into words
# words = nltk.word_tokenize(" ".join(data))

# # Compute the frequency distribution of words
# word_freq = FreqDist(words)

# # Get the most common words and their frequencies
# most_common = word_freq.most_common(5)

In [ ]:
# from nltk.corpus import stopwords

# stop_words = set(stopwords.words('english'))
# filtered_words = [word for word in words if word.lower() not in stop_words]

In [ ]:
# average_length = sum(len(word) for word in words) / len(words)

In [ ]:
# word_freq.plot(30, cumulative=False)
# plt.xlabel('Words')
# plt.ylabel('Frequency')
# plt.show()

In [ ]:
# result.at[0, 'counts_jakarta_reviews'] = 1
# result.at[0, 'counts_lombok_reviews'] = 1
# result.at[0, 'counts_bandung_reviews'] = 1
# result.at[0, 'counts_surabaya_reviews'] = 1

# result.at[1, 'counts_jakarta_reviews'] = 10
# result.at[1, 'counts_lombok_reviews'] = 23
# result.at[1, 'counts_bandung_reviews'] = 12
# result.at[1, 'counts_surabaya_reviews'] = 17

# result.at[2, 'counts_jakarta_reviews'] = 33
# result.at[2, 'counts_bandung_reviews'] = 51
# result.at[2, 'counts_surabaya_reviews'] = 47

# result.at[3, 'counts_bandung_reviews'] = 71

In [ ]:
# result_rooms.at[0, 'counts_jakarta_rooms'] = 1
# result_rooms.at[0, 'counts_lombok_rooms'] = 1
# result_rooms.at[0, 'counts_bandung_rooms'] = 1
# result_rooms.at[0, 'counts_surabaya_rooms'] = 1

# result_rooms.at[1, 'counts_jakarta_rooms'] = 3
# result_rooms.at[1, 'counts_lombok_rooms'] = 2
# result_rooms.at[1, 'counts_bandung_rooms'] = 3
# result_rooms.at[1, 'counts_surabaya_rooms'] = 5

# result_rooms.at[2, 'counts_bandung_rooms'] = 7
# result_rooms.at[2, 'counts_surabaya_rooms'] = 10

# result_rooms.at[3, 'counts_bandung_rooms'] = 11
# result_rooms.at[3, 'counts_surabaya_rooms'] = 17